VentaAutomoviles/Models/Carro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VentaAutomoviles.Models
{
    public class Carro
    {
        [Key]
        public int Id { get; set; }

        public string Modelo { get; set; }

        public string Cilindrada { get; set; }

        public string Marca { get; set; }

        public int Pasajeros { get; set; }

        public string Extras { get; set; }

        public string Rtv { get; set; }

        public string Marchamo { get; set; }
    }
}

VentaAutomoviles/Models/ErrorViewModel.cs
using System;

namespace VentaAutomoviles.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VentaAutomoviles/Controllers/AutoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VentaAutomoviles.Controllers
{
    public class AutoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Acerca()
        {
            return View();
        }

        public IActionResult Contactenos()
        {
            return View();
        }

        public IActionResult Servicios()
        {
            return View();
        }

        public IActionResult Iniciosesion()
        {
            return View();
        }
    }
}

VentaAutomoviles/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VentaAutomoviles.Models;

namespace VentaAutomoviles.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VentaAutomoviles/Views/Auto/Acerca.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="page-header">
    <h1>
        Acerca de Venta de Automoviles

        <small>La mejor venta del país</small>

    </h1>
</div>

VentaAutomoviles/Views/Auto/Contactenos.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Contactos</h1>
        <p class="lead">Puede contactarnos al número: 8910-8989 o al correo electronico irvin-go@hotmail.com</p>
    </div>
</div>

VentaAutomoviles/Views/Auto/Iniciosesion.cshtml
<form>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

VentaAutomoviles/Views/Auto/Servicios.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">Servicios</h5>
        <h6 class="card-subtitle mb-2 text-muted">A que nos dedicamos</h6>
        <p class="card-text">Venta de Automoviles es una empresa costarricense dedicada 100% a la venta de automoviles a nivel nacional. Nos encargamos de ofrecerle los mejores precios y además los mejores carros. Los esperemos..</p>
        <a href="#" class="card-link">Mas información</a>
        <a href="#" class="card-link">Comienza ya</a>
    </div>
</div>

VentaAutomoviles/Views/Carros/Create.cshtml
@model VentaAutomoviles.Models.Carro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cilindrada" class="control-label"></label>
                <input asp-for="Cilindrada" class="form-control" />
                <span asp-validation-for="Cilindrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pasajeros" class="control-label"></label>
                <input asp-for="Pasajeros" class="form-control" />
                <span asp-validation-for="Pasajeros" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Extras" class="control-label"></label>
                <input asp-for="Extras" class="form-control" />
                <span asp-validation-for="Extras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rtv" class="control-label"></label>
                <input asp-for="Rtv" class="form-control" />
                <span asp-validation-for="Rtv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marchamo" class="control-label"></label>
                <input asp-for="Marchamo" class="form-control" />
                <span asp-validation-for="Marchamo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VentaAutomoviles/Views/Carros/Delete.cshtml
@model VentaAutomoviles.Models.Carro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cilindrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cilindrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pasajeros)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pasajeros)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Extras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Extras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rtv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rtv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marchamo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marchamo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VentaAutomoviles/Views/Carros/Details.cshtml
@model VentaAutomoviles.Models.Carro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cilindrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cilindrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pasajeros)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pasajeros)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Extras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Extras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rtv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rtv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marchamo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marchamo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VentaAutomoviles/Views/Carros/Edit.cshtml
@model VentaAutomoviles.Models.Carro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cilindrada" class="control-label"></label>
                <input asp-for="Cilindrada" class="form-control" />
                <span asp-validation-for="Cilindrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pasajeros" class="control-label"></label>
                <input asp-for="Pasajeros" class="form-control" />
                <span asp-validation-for="Pasajeros" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Extras" class="control-label"></label>
                <input asp-for="Extras" class="form-control" />
                <span asp-validation-for="Extras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rtv" class="control-label"></label>
                <input asp-for="Rtv" class="form-control" />
                <span asp-validation-for="Rtv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marchamo" class="control-label"></label>
                <input asp-for="Marchamo" class="form-control" />
                <span asp-validation-for="Marchamo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VentaAutomoviles/Views/Carros/Index.cshtml
@model IEnumerable<VentaAutomoviles.Models.Carro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cilindrada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pasajeros)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Extras)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rtv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marchamo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cilindrada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pasajeros)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Extras)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rtv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marchamo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

VentaAutomoviles/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron">
    <h1 class="display-4">Bienvenidos</h1>
    <p class="lead">Venta de Automoviles de Costa Rica</p>
    <hr class="my-4">
    <p>Venta de Automoviles</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Mas información</a>
    </p>
</div>

VentaAutomoviles/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VentaAutomoviles</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VentaAutomoviles</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auto" asp-action="Acerca">Acerca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auto" asp-action="Contactenos">Contactos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auto" asp-action="Servicios">Servicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auto" asp-action="Iniciosesion">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VentaAutomoviles - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>